### ISSUE TITLE
dynamic lookup deprecated

### ISSUE THREAD

**Issue by mchugh19** [lelutin/puppet-sshd#1]
The module works great, but my puppet logs are filling up with lines:

Dynamic lookup of $sshd_allowed_users at /etc/puppet/modules/sshd/templates/sshd_config/Debian_squeeze.erb:193 is deprecated. Support will be removed in Puppet 2.8. Use a fully-qualified variable name (e.g., $classname::variable) or parameterized classes

I'm not exactly sure where the variable needs to be qualified. Thoughts?

**Comment by lelutin** [comment]
yep, those warnings are annoying... our modules use global variables like this all around and we are aware we need to change this for puppet 2.8 :\

See this issue regarding the subject: https://labs.riseup.net/code/issues/3333

(this site is where most of the puppet modules in my account are developped)

The general idea was to switch from global variables to using hiera to get data. However, we were waiing for it to get included in core by puppetlabs. There was a recent announcement saying that it would get fused in puppet (or something like it) so it looks promising.

if you'd like to try hiera and you modify the module to get rid of the global variables, I'd be glad to review your changes and propose them for inclusion to the community around the modules ;)
